// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CloseErrorWindow hides the error window.
 * @returns {$CancellablePromise<void>}
 */
export function CloseErrorWindow() {
    return $Call.ByID(3805492411);
}

/**
 * CloseTimerWindow destroys the window; hiding it would leak the WebView on reopen.
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function CloseTimerWindow(id) {
    return $Call.ByID(3036192156, id);
}

/**
 * CreateCategory creates a new category with the given name.
 * @param {string} name
 * @returns {$CancellablePromise<$models.Category | null>}
 */
export function CreateCategory(name) {
    return $Call.ByID(4163536593, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * CreateTask creates a new pending task. categoryID == 0 means no category.
 * @param {string} title
 * @param {string} description
 * @param {number} categoryID
 * @returns {$CancellablePromise<$models.Task | null>}
 */
export function CreateTask(title, description, categoryID) {
    return $Call.ByID(4224994508, title, description, categoryID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * DeleteCategory removes a category. Returns false if any tasks still reference it.
 * @param {number} id
 * @returns {$CancellablePromise<boolean>}
 */
export function DeleteCategory(id) {
    return $Call.ByID(988551738, id);
}

/**
 * DeleteTask removes a task by id.
 * @param {number} id
 * @returns {$CancellablePromise<boolean>}
 */
export function DeleteTask(id) {
    return $Call.ByID(2236295855, id);
}

/**
 * EditTask updates the title, description and category of a task. categoryID == 0 clears the category.
 * @param {number} id
 * @param {string} title
 * @param {string} description
 * @param {number} categoryID
 * @returns {$CancellablePromise<$models.Task | null>}
 */
export function EditTask(id, title, description, categoryID) {
    return $Call.ByID(2597083272, id, title, description, categoryID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ExportReport prompts for a save location and writes an xlsx report of all tasks.
 * @returns {$CancellablePromise<$models.ExportResult>}
 */
export function ExportReport() {
    return $Call.ByID(1503379429).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * FinishTask accumulates final elapsed time and marks the task done.
 * @param {number} id
 * @returns {$CancellablePromise<$models.Task | null>}
 */
export function FinishTask(id) {
    return $Call.ByID(4013664279, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetCategories returns all categories sorted alphabetically.
 * @returns {$CancellablePromise<$models.Category[]>}
 */
export function GetCategories() {
    return $Call.ByID(559270627).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetTasks returns all tasks sorted by created_at desc.
 * @returns {$CancellablePromise<$models.Task[]>}
 */
export function GetTasks() {
    return $Call.ByID(4294202735).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * OpenTimerWindow shows (or creates) the floating timer window for the given task.
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function OpenTimerWindow(id) {
    return $Call.ByID(1295391698, id);
}

/**
 * PauseTask accumulates elapsed time and pauses the task.
 * @param {number} id
 * @returns {$CancellablePromise<$models.Task | null>}
 */
export function PauseTask(id) {
    return $Call.ByID(3621607596, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * RenameCategory updates the name of an existing category.
 * @param {number} id
 * @param {string} name
 * @returns {$CancellablePromise<$models.Category | null>}
 */
export function RenameCategory(id, name) {
    return $Call.ByID(3179227807, id, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * StartTask pauses any currently running task then starts the given task.
 * @param {number} id
 * @returns {$CancellablePromise<$models.Task | null>}
 */
export function StartTask(id) {
    return $Call.ByID(1766862046, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.Category.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.Task.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.ExportResult.createFrom;
const $$createType5 = $Create.Array($$createType0);
const $$createType6 = $Create.Array($$createType2);
