// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../time/models.js";

export class Category {
    /**
     * Creates a new Category instance.
     * @param {Partial<Category>} [$$source = {}] - The source object to create the Category.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Category instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Category}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Category(/** @type {Partial<Category>} */($$parsedSource));
    }
}

export class Task {
    /**
     * Creates a new Task instance.
     * @param {Partial<Task>} [$$source = {}] - The source object to create the Task.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["description"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["categoryId"] = undefined;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {TaskStatus}
             */
            this["status"] = TaskStatus.$zero;
        }
        if (!("elapsedMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["elapsedMs"] = 0;
        }
        if (!("startedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time | null}
             */
            this["startedAt"] = null;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["createdAt"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {time$0.Time | null | undefined}
             */
            this["finishedAt"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Task instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Task}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Task(/** @type {Partial<Task>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const TaskStatus = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    StatusReadyToStart: "ready_to_start",
    StatusActive: "active",
    StatusPaused: "paused",
    StatusFinished: "finished",
};
